---

thermo_con_hecr-01:
  type: "thermo_con_hecr"

  environment:
    SYS: "XF:31ID1-CT"
    DEV: "{Mir:1-Env:1}"
    HOST: 10.69.58.105
    HECR_ASYNPORT: "tsrv1-p1"
    PREFIX: "XF:31ID1-CT{IOC:Env01}"
    ENGINEER: "Engineer Name"

  operations:
    - PORT_NAME: "${HECR_ASYNPORT}_INTERNAL_TEMPERATURE"
      MODBUS_FUNC: 3
      START_ADDR: 64
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_EXTERNAL_TEMPERATURE"
      MODBUS_FUNC: 3
      START_ADDR: 65
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_AVERAGE_TEMPERATURE"
      MODBUS_FUNC: 3
      START_ADDR: 66
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_STATUS_FLAG"
      MODBUS_FUNC: 3
      START_ADDR: 67
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_ALARM_FLAG_1"
      MODBUS_FUNC: 3
      START_ADDR: 68
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_ALARM_FLAG_2"
      MODBUS_FUNC: 3
      START_ADDR: 69
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_OUTPUT_RATIO"
      MODBUS_FUNC: 3
      START_ADDR: 70
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_CONTROL_OPERATION"
      MODBUS_FUNC: 6
      START_ADDR: 80
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_CONTROL_OPERATION_RB"
      MODBUS_FUNC: 3
      START_ADDR: 80
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_TARGET_TEMPERATURE"
      MODBUS_FUNC: 6
      START_ADDR: 81
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_TARGET_TEMPERATURE_RB"
      MODBUS_FUNC: 3
      START_ADDR: 81
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_OFFSET_VALUE"
      MODBUS_FUNC: 6
      START_ADDR: 82
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_OFFSET_VALUE_RB"
      MODBUS_FUNC: 3
      START_ADDR: 82
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_PB_RANGE"
      MODBUS_FUNC: 6
      START_ADDR: 83
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_PB_RANGE_RB"
      MODBUS_FUNC: 3
      START_ADDR: 83
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_I_CONSTANT"
      MODBUS_FUNC: 6
      START_ADDR: 85
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_I_CONSTANT_RB"
      MODBUS_FUNC: 3
      START_ADDR: 85
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_D_CONSTANT"
      MODBUS_FUNC: 6
      START_ADDR: 86
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_D_CONSTANT_RB"
      MODBUS_FUNC: 3
      START_ADDR: 86
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_HEAT_OUTPUT_LIMIT"
      MODBUS_FUNC: 6
      START_ADDR: 87
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_HEAT_OUTPUT_LIMIT_RB"
      MODBUS_FUNC: 3
      START_ADDR: 87
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "${HECR_ASYNPORT}_COOL_OUTPUT_LIMIT"
      MODBUS_FUNC: 6
      START_ADDR: 88
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"
    - PORT_NAME: "${HECR_ASYNPORT}_COOL_OUTPUT_LIMIT_RB"
      MODBUS_FUNC: 3
      START_ADDR: 88
      MODBUS_LEN: 1
      DATA_TYPE: "INT16"