---

eurotherm_rtc-01:
  type: eurotherm_rtc

  environment:
    SYS: "XF:31ID1-CT"
    DEV: "{RG:A1-RTC:1}"
    HOST: "192.168.111.222"
    EPC_ASYNPORT: "EPC3016"
    PREFIX: "XF:31ID1-CT{IOC:RTC01}"
    ENGINEER: "C. Engineer"

  operations:
    - PORT_NAME: "AI_PV"
      MODBUS_FUNC: 3
      START_ADDR: 289
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AI_PV_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 1932
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "IO1_PV_RB"
      MODBUS_FUNC: 3
      START_ADDR: 1952
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "IO1_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 1953
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_SP1"
      MODBUS_FUNC: 6
      START_ADDR: 24
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_SP1_RB"
      MODBUS_FUNC: 3
      START_ADDR: 24
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_CH1_PROP_BAND"
      MODBUS_FUNC: 6
      START_ADDR: 6
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_CH1_PROP_BAND_RB"
      MODBUS_FUNC: 3
      START_ADDR: 6
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_INTEGRAL_TIME"
      MODBUS_FUNC: 6
      START_ADDR: 8
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_INTEGRAL_TIME_RB"
      MODBUS_FUNC: 3
      START_ADDR: 8
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_DERIVATIVE_TIME"
      MODBUS_FUNC: 6
      START_ADDR: 9
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "LOOP_DERIVATIVE_TIME_RB"
      MODBUS_FUNC: 3
      START_ADDR: 9
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL1_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 2113
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL1_ACK"
      MODBUS_FUNC: 6
      START_ADDR: 2126
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL1_TYPE"
      MODBUS_FUNC: 3
      START_ADDR: 536
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL2_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 2137
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL2_ACK"
      MODBUS_FUNC: 6
      START_ADDR: 2150
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL2_TYPE"
      MODBUS_FUNC: 3
      START_ADDR: 537
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL3_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 2161
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL3_ACK"
      MODBUS_FUNC: 6
      START_ADDR: 2174
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL3_TYPE"
      MODBUS_FUNC: 3
      START_ADDR: 538
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL4_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 2185
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL4_ACK"
      MODBUS_FUNC: 6
      START_ADDR: 2198
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL4_TYPE"
      MODBUS_FUNC: 3
      START_ADDR: 539
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL5_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 2209
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL5_ACK"
      MODBUS_FUNC: 6
      START_ADDR: 2222
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL5_TYPE"
      MODBUS_FUNC: 3
      START_ADDR: 2208
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL6_STATUS"
      MODBUS_FUNC: 3
      START_ADDR: 2233
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL6_ACK"
      MODBUS_FUNC: 6
      START_ADDR: 2246
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "AL6_TYPE"
      MODBUS_FUNC: 3
      START_ADDR: 2232
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "INSTRUMENT_MODE"
      MODBUS_FUNC: 6
      START_ADDR: 199
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "INSTRUMENT_MODE_RB"
      MODBUS_FUNC: 3
      START_ADDR: 199
      MODBUS_LEN: 1
      DATA_TYPE: "UINT16"
    - PORT_NAME: "ACCESS_PASSWORD"
      MODBUS_FUNC: 16
      START_ADDR: 21760
      MODBUS_LEN: 9
      DATA_TYPE: "ZSTRING_HIGH_LOW"